"""Canonical schema — design doc §5."""

from foodos.schema.base import Base, TimestampMixin, utcnow
from foodos.schema.enums import (
    ActionType,
    BatchState,
    CaptureMethod,
    ChannelType,
    Confidence,
    Horizon,
    InventoryEventType,
    RecommendationStatus,
    RescueOfferStatus,
    SiteType,
    Track,
    WasteReason,
    WasteStage,
)
from foodos.schema.tables import (
    Batch,
    Channel,
    DemandContext,
    Forecast,
    InventoryEvent,
    MarketPrice,
    ModelRun,
    Organization,
    Product,
    ProductionRecord,
    Recipe,
    RecipeLine,
    Recommendation,
    RecommendationOutcome,
    RescueOffer,
    RiskScore,
    SalesRecord,
    ShelfLifeProfile,
    Site,
    StorageReading,
    StorageZone,
    WasteEvent,
)

__all__ = [
    "Base",
    "TimestampMixin",
    "utcnow",
    # enums
    "ActionType",
    "BatchState",
    "CaptureMethod",
    "ChannelType",
    "Confidence",
    "Horizon",
    "InventoryEventType",
    "RecommendationStatus",
    "RescueOfferStatus",
    "SiteType",
    "Track",
    "WasteReason",
    "WasteStage",
    # tables
    "Organization",
    "Site",
    "Product",
    "Recipe",
    "RecipeLine",
    "ShelfLifeProfile",
    "StorageZone",
    "Batch",
    "InventoryEvent",
    "StorageReading",
    "SalesRecord",
    "ProductionRecord",
    "DemandContext",
    "WasteEvent",
    "ModelRun",
    "Forecast",
    "RiskScore",
    "Recommendation",
    "RecommendationOutcome",
    "Channel",
    "RescueOffer",
    "MarketPrice",
]
